# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calcHsExtras.ui',
# licensing of 'calcHsExtras.ui' applies.
#
# Created: Tue Dec 24 19:24:09 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_CalcMainWindow(object):
    def setupUi(self, CalcMainWindow):
        CalcMainWindow.setObjectName("CalcMainWindow")
        CalcMainWindow.resize(452, 365)
        self.calcular_pbt = QtWidgets.QPushButton(CalcMainWindow)
        self.calcular_pbt.setGeometry(QtCore.QRect(20, 300, 411, 41))
        self.calcular_pbt.setAutoDefault(True)
        self.calcular_pbt.setDefault(True)
        self.calcular_pbt.setObjectName("calcular_pbt")
        self.hsextras = QtWidgets.QLabel(CalcMainWindow)
        self.hsextras.setGeometry(QtCore.QRect(20, 57, 132, 16))
        self.hsextras.setObjectName("hsextras")
        self.valorjornada_LEd = QtWidgets.QLineEdit(CalcMainWindow)
        self.valorjornada_LEd.setGeometry(QtCore.QRect(262, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.valorjornada_LEd.setFont(font)
        self.valorjornada_LEd.setMouseTracking(True)
        self.valorjornada_LEd.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.valorjornada_LEd.setToolTipDuration(-1)
        self.valorjornada_LEd.setFrame(False)
        self.valorjornada_LEd.setCursorPosition(0)
        self.valorjornada_LEd.setProperty("valJornada", 0)
        self.valorjornada_LEd.setObjectName("valorjornada_LEd")
        self.valJornada_L = QtWidgets.QLabel(CalcMainWindow)
        self.valJornada_L.setGeometry(QtCore.QRect(20, 20, 236, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.valJornada_L.setFont(font)
        self.valJornada_L.setTextFormat(QtCore.Qt.AutoText)
        self.valJornada_L.setObjectName("valJornada_L")
        self.TotalaCobrar_LCD = QtWidgets.QLCDNumber(CalcMainWindow)
        self.TotalaCobrar_LCD.setGeometry(QtCore.QRect(130, 250, 291, 41))
        self.TotalaCobrar_LCD.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TotalaCobrar_LCD.setSmallDecimalPoint(False)
        self.TotalaCobrar_LCD.setProperty("intValue", 0)
        self.TotalaCobrar_LCD.setObjectName("TotalaCobrar_LCD")
        self.cobraras_L = QtWidgets.QLabel(CalcMainWindow)
        self.cobraras_L.setGeometry(QtCore.QRect(20, 270, 123, 16))
        self.cobraras_L.setObjectName("cobraras_L")
        self.hnocturno_checkbox = QtWidgets.QCheckBox(CalcMainWindow)
        self.hnocturno_checkbox.setEnabled(True)
        self.hnocturno_checkbox.setGeometry(QtCore.QRect(20, 145, 243, 20))
        self.hnocturno_checkbox.setMinimumSize(QtCore.QSize(81, 0))
        self.hnocturno_checkbox.setObjectName("hnocturno_checkbox")
        self.duracion_Jornada_spinBox = QtWidgets.QSpinBox(CalcMainWindow)
        self.duracion_Jornada_spinBox.setGeometry(QtCore.QRect(160, 50, 51, 22))
        self.duracion_Jornada_spinBox.setMinimum(1)
        self.duracion_Jornada_spinBox.setMaximum(24)
        self.duracion_Jornada_spinBox.setProperty("value", 12)
        self.duracion_Jornada_spinBox.setObjectName("duracion_Jornada_spinBox")
        self.splitter = QtWidgets.QSplitter(CalcMainWindow)
        self.splitter.setGeometry(QtCore.QRect(20, 110, 401, 24))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.dia_hora_entrada = QtWidgets.QDateTimeEdit(self.splitter)
        self.dia_hora_entrada.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dia_hora_entrada.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dia_hora_entrada.setCalendarPopup(True)
        self.dia_hora_entrada.setObjectName("dia_hora_entrada")
        self.hasta_L = QtWidgets.QLabel(self.splitter)
        self.hasta_L.setObjectName("hasta_L")
        self.dia_hora_salida = QtWidgets.QDateTimeEdit(self.splitter)
        self.dia_hora_salida.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dia_hora_salida.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dia_hora_salida.setCalendarPopup(True)
        self.dia_hora_salida.setObjectName("dia_hora_salida")
        self.Entrada_FechaHora_label = QtWidgets.QLabel(CalcMainWindow)
        self.Entrada_FechaHora_label.setGeometry(QtCore.QRect(20, 91, 119, 20))
        self.Entrada_FechaHora_label.setObjectName("Entrada_FechaHora_label")
        self.Salida_FechaHora_label = QtWidgets.QLabel(CalcMainWindow)
        self.Salida_FechaHora_label.setGeometry(QtCore.QRect(310, 90, 114, 24))
        self.Salida_FechaHora_label.setObjectName("Salida_FechaHora_label")
        self.porcentaje_hs_extras_spinBox = QtWidgets.QSpinBox(CalcMainWindow)
        self.porcentaje_hs_extras_spinBox.setGeometry(QtCore.QRect(380, 140, 41, 22))
        self.porcentaje_hs_extras_spinBox.setMinimum(0)
        self.porcentaje_hs_extras_spinBox.setMaximum(150)
        self.porcentaje_hs_extras_spinBox.setSingleStep(10)
        self.porcentaje_hs_extras_spinBox.setProperty("value", 50)
        self.porcentaje_hs_extras_spinBox.setObjectName("porcentaje_hs_extras_spinBox")
        self.porcentaje_hs_ext_L = QtWidgets.QLabel(CalcMainWindow)
        self.porcentaje_hs_ext_L.setGeometry(QtCore.QRect(248, 145, 132, 16))
        self.porcentaje_hs_ext_L.setObjectName("porcentaje_hs_ext_L")
        self.gridLayoutWidget = QtWidgets.QWidget(CalcMainWindow)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 170, 415, 40))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.sub_totales_gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.sub_totales_gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.sub_totales_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.sub_totales_gridLayout.setObjectName("sub_totales_gridLayout")
        self.por_hs_extra_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.por_hs_extra_label.setFont(font)
        self.por_hs_extra_label.setObjectName("por_hs_extra_label")
        self.sub_totales_gridLayout.addWidget(self.por_hs_extra_label, 1, 5, 1, 1)
        self.pesos_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.pesos_label.setFont(font)
        self.pesos_label.setObjectName("pesos_label")
        self.sub_totales_gridLayout.addWidget(self.pesos_label, 1, 2, 1, 1)
        self.delascuales_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.delascuales_label.setFont(font)
        self.delascuales_label.setObjectName("delascuales_label")
        self.sub_totales_gridLayout.addWidget(self.delascuales_label, 0, 3, 1, 1)
        self.a_un_valor = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.a_un_valor.setFont(font)
        self.a_un_valor.setObjectName("a_un_valor")
        self.sub_totales_gridLayout.addWidget(self.a_un_valor, 1, 3, 1, 1)
        self.hasTrabajado = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.hasTrabajado.setFont(font)
        self.hasTrabajado.setObjectName("hasTrabajado")
        self.sub_totales_gridLayout.addWidget(self.hasTrabajado, 0, 0, 1, 1)
        self.son_extras_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.son_extras_label.setFont(font)
        self.son_extras_label.setObjectName("son_extras_label")
        self.sub_totales_gridLayout.addWidget(self.son_extras_label, 0, 5, 1, 1)
        self.gananciaHsExtra_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.gananciaHsExtra_label.setFont(font)
        self.gananciaHsExtra_label.setObjectName("gananciaHsExtra_label")
        self.sub_totales_gridLayout.addWidget(self.gananciaHsExtra_label, 1, 1, 1, 1)
        self.cobrarasXhsEx_L = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cobrarasXhsEx_L.setObjectName("cobrarasXhsEx_L")
        self.sub_totales_gridLayout.addWidget(self.cobrarasXhsEx_L, 1, 0, 1, 1)
        self.horas_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.horas_label.setFont(font)
        self.horas_label.setObjectName("horas_label")
        self.sub_totales_gridLayout.addWidget(self.horas_label, 0, 2, 1, 1)
        self.horasTrabajadas_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.horasTrabajadas_label.setFont(font)
        self.horasTrabajadas_label.setObjectName("horasTrabajadas_label")
        self.sub_totales_gridLayout.addWidget(self.horasTrabajadas_label, 0, 1, 1, 1)
        self.son_hs_extras_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.son_hs_extras_label.setFont(font)
        self.son_hs_extras_label.setObjectName("son_hs_extras_label")
        self.sub_totales_gridLayout.addWidget(self.son_hs_extras_label, 0, 4, 1, 1)
        self.valor_x_hsextra_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.valor_x_hsextra_label.setFont(font)
        self.valor_x_hsextra_label.setObjectName("valor_x_hsextra_label")
        self.sub_totales_gridLayout.addWidget(self.valor_x_hsextra_label, 1, 4, 1, 1)

        self.retranslateUi(CalcMainWindow)
        QtCore.QObject.connect(self.valorjornada_LEd, QtCore.SIGNAL("returnPressed()"), self.calcular_pbt.update)
        QtCore.QObject.connect(self.duracion_Jornada_spinBox, QtCore.SIGNAL("valueChanged(int)"), CalcMainWindow.update)
        QtCore.QObject.connect(self.hnocturno_checkbox, QtCore.SIGNAL("clicked(bool)"), self.duracion_Jornada_spinBox.update)
        QtCore.QMetaObject.connectSlotsByName(CalcMainWindow)
        CalcMainWindow.setTabOrder(self.valorjornada_LEd, self.duracion_Jornada_spinBox)
        CalcMainWindow.setTabOrder(self.duracion_Jornada_spinBox, self.dia_hora_entrada)
        CalcMainWindow.setTabOrder(self.dia_hora_entrada, self.dia_hora_salida)
        CalcMainWindow.setTabOrder(self.dia_hora_salida, self.calcular_pbt)
        CalcMainWindow.setTabOrder(self.calcular_pbt, self.hnocturno_checkbox)

    def retranslateUi(self, CalcMainWindow):
        CalcMainWindow.setWindowTitle(QtWidgets.QApplication.translate("CalcMainWindow", "Calculadora de jornada laboral", None, -1))
        self.calcular_pbt.setText(QtWidgets.QApplication.translate("CalcMainWindow", "Calcular Total", None, -1))
        self.calcular_pbt.setShortcut(QtWidgets.QApplication.translate("CalcMainWindow", "Return", None, -1))
        self.hsextras.setText(QtWidgets.QApplication.translate("CalcMainWindow", "jornada de 10 o 12hs ?", None, -1))
        self.valorjornada_LEd.setToolTip(QtWidgets.QApplication.translate("CalcMainWindow", "escribe el valor de la jornada de 12hs, usando \".\" punto para los decimales.", None, -1))
        self.valorjornada_LEd.setWhatsThis(QtWidgets.QApplication.translate("CalcMainWindow", "<html><head/><body><p><br/></p></body></html>", None, -1))
        self.valorjornada_LEd.setInputMask(QtWidgets.QApplication.translate("CalcMainWindow", "00009x00", None, -1))
        self.valorjornada_LEd.setPlaceholderText(QtWidgets.QApplication.translate("CalcMainWindow", "$0000.00", None, -1))
        self.valJornada_L.setText(QtWidgets.QApplication.translate("CalcMainWindow", "Honoraios por jornada regular de hs", None, -1))
        self.cobraras_L.setText(QtWidgets.QApplication.translate("CalcMainWindow", "cobrarás en Total =", None, -1))
        self.hnocturno_checkbox.setToolTip(QtWidgets.QApplication.translate("CalcMainWindow", "chequear si rije para el proyecto el calculo diferenciado de horas nocturnas por convenio. \n"
" En cine: Horario nocturno: 21 a 06 hs (durante ese lapso se computa 1 hora por cada 50 minutos trabajados)", None, -1))
        self.hnocturno_checkbox.setText(QtWidgets.QApplication.translate("CalcMainWindow", "considerar regla de horario nocturno?", None, -1))
        self.duracion_Jornada_spinBox.setToolTip(QtWidgets.QApplication.translate("CalcMainWindow", "horas incluidas por jornada regular", None, -1))
        self.dia_hora_entrada.setDisplayFormat(QtWidgets.QApplication.translate("CalcMainWindow", "d/M/yyyy H:mm", None, -1))
        self.hasta_L.setText(QtWidgets.QApplication.translate("CalcMainWindow", " hasta", None, -1))
        self.dia_hora_salida.setDisplayFormat(QtWidgets.QApplication.translate("CalcMainWindow", "d/M/yyyy H:mm", None, -1))
        self.Entrada_FechaHora_label.setText(QtWidgets.QApplication.translate("CalcMainWindow", "Fecha y hora de entrada", None, -1))
        self.Salida_FechaHora_label.setText(QtWidgets.QApplication.translate("CalcMainWindow", "Fecha y hora de salida", None, -1))
        self.porcentaje_hs_extras_spinBox.setToolTip(QtWidgets.QApplication.translate("CalcMainWindow", "usualmente es 50% extra", None, -1))
        self.porcentaje_hs_ext_L.setText(QtWidgets.QApplication.translate("CalcMainWindow", "porcentaje por hs extras =", None, -1))
        self.por_hs_extra_label.setText(QtWidgets.QApplication.translate("CalcMainWindow", "x hora extra", None, -1))
        self.pesos_label.setText(QtWidgets.QApplication.translate("CalcMainWindow", "$", None, -1))
        self.delascuales_label.setText(QtWidgets.QApplication.translate("CalcMainWindow", "De las cuales:", None, -1))
        self.a_un_valor.setText(QtWidgets.QApplication.translate("CalcMainWindow", "A valor de:", None, -1))
        self.hasTrabajado.setText(QtWidgets.QApplication.translate("CalcMainWindow", "trabajaste un total de: ", None, -1))
        self.son_extras_label.setText(QtWidgets.QApplication.translate("CalcMainWindow", "son extras", None, -1))
        self.gananciaHsExtra_label.setText(QtWidgets.QApplication.translate("CalcMainWindow", "0000", None, -1))
        self.cobrarasXhsEx_L.setText(QtWidgets.QApplication.translate("CalcMainWindow", "cobrarás por hs extra:", None, -1))
        self.horas_label.setText(QtWidgets.QApplication.translate("CalcMainWindow", " hs ", None, -1))
        self.horasTrabajadas_label.setText(QtWidgets.QApplication.translate("CalcMainWindow", "0000", None, -1))
        self.son_hs_extras_label.setText(QtWidgets.QApplication.translate("CalcMainWindow", "0000", None, -1))
        self.valor_x_hsextra_label.setText(QtWidgets.QApplication.translate("CalcMainWindow", "0000", None, -1))

